### ISSUE TITLE
varwatch dont build with maven 3.6.0

### ISSUE THREAD

**Issue by david2905** [broderF/varwatch#7]
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/config/ConfigurationDaoSQL.java:[10,32] error: package com.ikmb.core.data.config does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/config/ConfigurationDaoSQL.java:[11,32] error: package com.ikmb.core.data.config does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/config/ConfigurationDaoSQL.java:[12,32] error: package com.ikmb.core.data.config does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/config/ConfigurationDaoSQL.java:[22,44] error: cannot find symbol
[ERROR]  class ConfigurationDao
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/config/ConfigurationDaoSQL.java:[28,16] error: cannot find symbol
[ERROR]  class ConfigurationDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/config/ConfigurationDaoSQL.java:[35,23] error: cannot find symbol
[ERROR]  class ConfigurationDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/config/ConfigurationDaoSQL.java:[53,16] error: cannot find symbol
[ERROR]  class ConfigurationDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/config/ConfigurationDaoSQL.java:[60,35] error: cannot find symbol
[ERROR]  class ConfigurationDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/client/ClientDaoSQL.java:[11,37] error: package com.ikmb.core.data.auth.client does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/client/ClientDaoSQL.java:[12,37] error: package com.ikmb.core.data.auth.client does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/client/ClientDaoSQL.java:[22,37] error: cannot find symbol
[ERROR]  class ClientDao
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/client/ClientDaoSQL.java:[28,11] error: cannot find symbol
[ERROR]  class ClientDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/client/ClientDaoSQL.java:[41,21] error: cannot find symbol
[ERROR]  class ClientDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/client/ClientDaoSQL.java:[45,34] error: cannot find symbol
[ERROR]  class ClientDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/client/ClientDaoSQL.java:[55,11] error: cannot find symbol
[ERROR]  class ClientDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[9,35] error: package com.ikmb.core.data.auth.user does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[10,33] error: package com.ikmb.core.data.dataset does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[11,33] error: package com.ikmb.core.data.dataset does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[12,33] error: package com.ikmb.core.data.dataset does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[13,29] error: package com.ikmb.core.data.hpo does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[26,38] error: cannot find symbol
[ERROR]  class DatasetDao
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[31,21] error: cannot find symbol
[ERROR]  class DatasetDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[39,33] error: cannot find symbol
[ERROR]  class DatasetDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[39,11] error: cannot find symbol
[ERROR]  class DatasetDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[48,11] error: cannot find symbol
[ERROR]  class DatasetDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[57,23] error: cannot find symbol
[ERROR]  class DatasetDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[61,24] error: cannot find symbol
[ERROR]  class DatasetDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[66,45] error: cannot find symbol
[ERROR]  class DatasetDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[66,16] error: cannot find symbol
[ERROR]  class DatasetDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[73,42] error: cannot find symbol
[ERROR]  class DatasetDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/dataset/DatasetDaoSQL.java:[80,11] error: cannot find symbol
[ERROR]  class DatasetDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/hpo/HPOTermDaoSQL.java:[10,29] error: package com.ikmb.core.data.hpo does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/hpo/HPOTermDaoSQL.java:[11,29] error: package com.ikmb.core.data.hpo does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/hpo/HPOTermDaoSQL.java:[12,29] error: package com.ikmb.core.data.hpo does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/hpo/HPOTermDaoSQL.java:[13,29] error: package com.ikmb.core.data.hpo does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/hpo/HPOTermDaoSQL.java:[33,38] error: cannot find symbol
[ERROR]  class HPOTermDao
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/hpo/HPOTermDaoSQL.java:[38,21] error: cannot find symbol
[ERROR]  class HPOTermDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/hpo/HPOTermDaoSQL.java:[113,11] error: cannot find symbol
[ERROR]  class HPOTermDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/hpo/HPOTermDaoSQL.java:[128,32] error: cannot find symbol
[ERROR]  class HPOTermDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/varianteffect/VariantEffectDaoSQL.java:[10,39] error: package com.ikmb.core.data.varianteffect does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/varianteffect/VariantEffectDaoSQL.java:[11,39] error: package com.ikmb.core.data.varianteffect does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/varianteffect/VariantEffectDaoSQL.java:[18,44] error: cannot find symbol
[ERROR]  class VariantEffectDao
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/varianteffect/VariantEffectDaoSQL.java:[24,24] error: cannot find symbol
[ERROR]  class VariantEffectDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[9,37] error: package com.ikmb.core.data.auth.client does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[10,36] error: package com.ikmb.core.data.auth.token does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[11,35] error: package com.ikmb.core.data.auth.user does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[12,33] error: package com.ikmb.core.data.dataset does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[13,33] error: package com.ikmb.core.data.ensembl does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[14,29] error: package com.ikmb.core.data.hpo does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[15,29] error: package com.ikmb.core.data.hpo does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[16,34] error: package com.ikmb.core.data.matching does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[17,38] error: package com.ikmb.core.data.reference_db does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[18,36] error: package com.ikmb.core.data.transcript does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[19,33] error: package com.ikmb.core.data.variant does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[20,33] error: package com.ikmb.core.data.variant does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[21,39] error: package com.ikmb.core.data.varianteffect does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[22,30] error: package com.ikmb.core.data.wipe does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[23,43] error: package com.ikmb.core.data.workflow.analysis does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[24,38] error: package com.ikmb.core.data.workflow.job does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/guice/VarWatchMainModule.java:[25,41] error: package com.ikmb.core.data.workflow.worker does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[10,35] error: package com.ikmb.core.data.auth.user does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[11,33] error: package com.ikmb.core.data.dataset does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[12,32] error: package com.ikmb.core.data.family does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[13,30] error: package com.ikmb.core.data.gene does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[14,34] error: package com.ikmb.core.data.matching does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[15,34] error: package com.ikmb.core.data.matching does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[16,34] error: package com.ikmb.core.data.matching does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[17,33] error: package com.ikmb.core.data.pathway does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[18,36] error: package com.ikmb.core.data.transcript does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[19,33] error: package com.ikmb.core.data.variant does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[21,33] error: package com.ikmb.core.data.variant does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[22,39] error: package com.ikmb.core.data.varianteffect does not exist
[ERROR] /scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[42,43] error: cannot find symbol
[ERROR]  class MatchVariantDao
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[50,11] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[54,44] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[54,16] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[121,43] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[121,16] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[134,52] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[134,16] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[189,54] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[189,16] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[199,46] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[199,16] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[207,26] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[212,58] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[212,16] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[233,52] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[233,16] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[253,60] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[253,16] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[292,54] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[292,16] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[331,34] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[348,58] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[348,16] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[357,23] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[362,51] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[362,16] error: cannot find symbol
[ERROR]  class MatchVariantDaoSQL
/scratch/local2/tmp-schrader/varwatch/varwatch-sql/src/main/java/com/ikmb/sql/data/matching/MatchVariantDaoSQL.java:[368,11] error: cannot find symbol
[INFO] 100 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for varwatch 1.0-SNAPSHOT:
[INFO] 
[INFO] varwatch-core ...................................... SUCCESS [ 48.913 s]
[INFO] varwatch-sql ....................................... FAILURE [  0.920 s]
```

**Comment by david2905** [comment]
successful build with maven 3.3.9

README brings to maven 3.6.0
